# Generated by Django 4.2.4 on 2023-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/slider_images')),
                ('Deal', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('NEW ARRAIVAL', 'NEW ARRAIVAL')], max_length=100)),
                ('Sale', models.IntegerField()),
                ('Brand', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=30)),
            ],
        ),
    ]
