# Generated by Django 4.2.4 on 2023-08-16 18:41

from django.db import migrations, models
import django.db.models.deletion
import ecom_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='media/Category/Category_img')),
                ('cat_logo', models.ImageField(upload_to='media/Category/Category_logo')),
                ('cat_banner', models.ImageField(upload_to='media/Category/Featured_banners')),
            ],
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Brand',
            new_name='Discount_Offer',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='Sale',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_Image', models.ImageField(upload_to='media/products_images')),
                ('Product_Price', models.CharField(max_length=10)),
                ('Product_description', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='Featured_Product',
            field=models.ForeignKey(default=1, on_delete=ecom_app.models.Category, to='ecom_app.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='Url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Banner_Url', to='ecom_app.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.category'),
        ),
    ]
