# Generated by Django 4.2.4 on 2023-08-17 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Featured_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuredcat', to='ecom_app.category'),
        ),
    ]
