# Generated by Django 4.2.4 on 2023-08-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_alter_banner_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='Featured_Product',
            new_name='Featured_cat',
        ),
    ]
