# Generated by Django 4.2.4 on 2023-08-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_remove_banner_image_remove_banner_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='Banner',
            field=models.ImageField(default=1, upload_to='media/Category/Featured_banners'),
            preserve_default=False,
        ),
    ]
