# Generated by Django 4.2.4 on 2023-08-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_remove_category_cat_banner_banner_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
