# Generated by Django 4.2.4 on 2023-08-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_banner_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='Title',
        ),
    ]
