# Generated by Django 4.2.4 on 2023-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_remove_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Discount_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
