# Generated by Django 4.2.4 on 2023-08-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0011_main_caegory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Main_Caegory',
        ),
        migrations.AddField(
            model_name='category',
            name='Sub_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom_app.main_category'),
            preserve_default=False,
        ),
    ]
