# Generated by Django 4.2.4 on 2023-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0013_rename_sub_cat_category_main_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_category',
            name='Description',
        ),
        migrations.AddField(
            model_name='main_category',
            name='Image',
            field=models.ImageField(default=1, upload_to='media/Category/categoty_main/Category_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_category',
            name='cat_logo',
            field=models.ImageField(default=1, upload_to='media/Category/categoty_main/Category_logo'),
            preserve_default=False,
        ),
    ]
