# Generated by Django 4.2.4 on 2023-08-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0015_remove_category_cat_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_Description',
        ),
        migrations.AlterField(
            model_name='banner',
            name='Featured_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuredcat', to='ecom_app.main_category'),
        ),
    ]
