# Generated by Django 4.2.4 on 2023-08-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0017_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_description',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Price',
        ),
        migrations.AddField(
            model_name='product',
            name='Availablity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Featured_image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Information',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Total_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_url', models.CharField(max_length=200)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Aditional_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specification', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=100)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecom_app.section'),
            preserve_default=False,
        ),
    ]
