# Generated by Django 4.2.4 on 2023-08-18 08:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0018_section_rename_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Information',
            field=tinymce.models.HTMLField(),
        ),
    ]
