# Generated by Django 4.2.4 on 2023-08-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0020_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='ecom_app_Product',
        ),
    ]
